# Generated by Django 3.2.7 on 2021-10-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='location',
        ),
    ]
